version: '3.8'

services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "8081:80"
      - "8082:8080"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/html:/usr/share/nginx/html:ro

  zabbix-agent:
    image: zabbix/zabbix-agent2:latest
    container_name: zabbix-agent2
    restart: always
    user: root
    ports:
      - "10050:10050"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - ZBX_SERVER_HOST=192.168.31.81:10051
      - ZBX_HOSTNAME=Zabbix server
      
